version: '3.7'

services:
  database:
    image: mysql
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - 3308:3306
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: geheim
      MYSQL_DATABASE: rheinjug2

  minio:
    image: minio/minio
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    command: "server /data/"

  app:
    image: gradle:jdk11
    restart: always
    working_dir: /rheinjug2
    volumes:
      - ./:/rheinjug2
    ports:
      - 8080:8080
    depends_on:
      - database
      - minio
    command: gradle bootRun --debug
    #command: sh -c "cd ./build/libs && java -jar rheinjug2-0.0.1-SNAPSHOT.jar"

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  my-db:
  data1-1:
  data1-2:
