= Management Summary
WS19/20
:icons: font
:icon-set: octicon
:source-highlighter: rouge
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Problemstatement

Die manuelle Korrektur der Abgaben und die Scheinvergabe ist zu umständlich.
Durch nicht fachgerechte Überprüfung kann nicht gewährleistet werden, dass eine Abgabe doppelt eingelöst wird.

== Wesentliche Ziele und Features

=== Ziele:

- Belegen der Veranstaltungen und Abgabe der Zusammenfassungen an einer Stelle für die Studenten
- Automatisierte Scheinvergabe +++<u>ohne</u>+++ doppeltes Einlösen der gleichen Veranstaltung
- Übersicht über Abgaben und deren zugehörigen Veranstaltungen für Organisatoren
- Bestätigung der Abgaben durch Organisatoren

=== Features:

- Abrufen der Events über meetup.com
- Übersicht über belegte Veranstaltungen
- Bestätigung der Abgaben per Knopfdruck

NOTE: Obwohl aus Gründen der Lesbarkeit die männliche Form gewählt wurde, beziehen sich die Angaben auf Angehörige aller Geschlechter.