# .github/workflows/gradle.yml

name: Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-11
        with:
          args: check
      - uses: actions/upload-artifact@v1
        if: success() || failure()
        with:
          name: build-reports
          path: build/reports
