# .github/workflows/gradle.yml

name: Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run tests
        run: gradle check
      - uses: actions/upload-artifact@v1
        with:
          name: test-index-html
          path: home/runner/work/abschlussprojekt-grossbrandtmeister/abschlussprojekt-grossbrandtmeister/build/reports/tests/test/index.html
